log_level: debug
log_source: false

http:
    port: 9000

postgres:
    db_name: quiz
    host: 127.0.0.1
    # host: pro.sealur.ru
    port: 5436
    # port: 5432
    ssl_mode: disable
    username: postgres
